name: Quick Check

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  quick-test:
    name: Quick Test
    runs-on: ubuntu-latest
    timeout-minutes: 10
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable
    
    - name: Cache cargo
      uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-cargo-quick-${{ hashFiles('**/Cargo.lock') }}
    
    - name: Quick checks
      run: |
        echo "Running quick CI checks..."
        cargo fmt -- --check
        cargo clippy --all-targets --all-features
        cargo test --lib
        echo "✅ All quick checks passed!"